### ISSUE TITLE
having trouble installing `gem asciidoctor mathematical`

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/docs-templates#4]
I installed cmake which wasn't in the windows instructions, as I got an error from trying to install `gem asciidoctor mathematical` but it hasn't solved the problem. 

https://github.com/Kitware/CMake/releases/download/v3.21.0-rc3/cmake-3.21.0-rc3-windows-x86_64.msi

This is most likely the problem:

`  Could NOT find BISON (missing: BISON_EXECUTABLE)`

PS C:\Users\t00346040\docs-templates> gem install asciidoctor-mathematical
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing asciidoctor-mathematical:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mathematical-1.6.14/ext/mathematical
C:/Ruby30-x64/bin/ruby.exe -I C:/Ruby30-x64/lib/ruby/3.0.0 -r ./siteconf20210712-1300-s3lk9a.rb extconf.rb
checking for cmake... yes
checking for -lxml2... no
checking for -lpangocairo-1.0... no
checking for libxml/tree.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
checking for libxml/parser.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
checking for libxml/xpath.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
checking for libxml/xpathInternals.h in /include/libxml2,/usr/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- The C compiler identification is MSVC 19.29.30038.1
-- The CXX compiler identification is MSVC 19.29.30038.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:19 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BISON (missing: BISON_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindBISON.cmake:306 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:61 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mathematical-1.6.14/ext/mathematical/mtex2MML/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'libmtex2MML_static'.  Stop.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby30-x64/bin/$(RUBY_BASE_NAME)
        --with-xml2-dir
        --without-xml2-dir
        --with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
        --with-xml2lib
        --without-xml2lib
        --with-pangocairo-1.0-dir
        --without-pangocairo-1.0-dir
        --with-pangocairo-1.0-include
        --without-pangocairo-1.0-include=${pangocairo-1.0-dir}/include
        --with-pangocairo-1.0-lib
        --without-pangocairo-1.0-lib=${pangocairo-1.0-dir}/lib
        --with-pangocairo-1.0lib
        --without-pangocairo-1.0lib
        --use-system-mtex2MML
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:494:in `realpath': No such file or directory @ realpath_rec - C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mathematical-1.6.14/ext/mathematical/mtex2MML/build/libmtex2MML.a (Errno::ENOENT)
        from C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:494:in `copy_entry'
        from C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:471:in `block in cp_r'
        from C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
        from C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1611:in `fu_each_src_dest0'
        from C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
        from C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:470:in `cp_r'
        from extconf.rb:80:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/mathematical-1.6.14/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mathematical-1.6.14 for inspection.
Results logged to C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/mathematical-1.6.14/gem_make.out
PS C:\Users\t00346040\docs-templates>

**Comment by elisa-riscv** [comment]
You are using Ruby 3.0.0. 

Can you try installing RVM and Ruby 2.5.x per the instructions?

**Comment by tariqkurd-repo** [comment]
The problem is that there's no obvious download for ruby 2.5.x, it seems to be too old so it's not listed any more. Can you post a link to the correct download?

**Comment by elisa-riscv** [comment]
I used RVM to install Ruby 2.5.9:
```
rvm install 2.5.9
```
No need to look for anything. The commands are in the readme. If you want more information on RVM : https://rvm.io/rvm/install .

**Comment by elisa-riscv** [comment]
These are good questions. I don't have a Windows machine and will ask a member who does so that I can document the answer.

**Comment by elisa-riscv** [comment]
@cetola Thanks.
